# Generated by Django 5.0.7 on 2024-07-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_certificate_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
