# Generated by Django 5.0.7 on 2024-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
